#!/usr/bin/env python

import subprocess
import sys

# Obtener la ruta al intérprete de Python dentro del entorno virtual
python_executable = sys.executable

# Ejecutar el comando para ejecutar pruebas utilizando el intérprete de Python del entorno virtual
result = subprocess.run([python_executable, '-m', 'flake8', 'main.py'], stdout=subprocess.PIPE)

if result.returncode != 0:
    print("¡Se encontraron problemas de estilo en el código!")
    print(result.stdout.decode())
    exit(1)
else: 
    print("Revision de estilo finalizado, continuando")